clone_depth: 1
image: Visual Studio 2017
configuration: Release
platform: x64
version: 0.1.{build}.0
pull_requests:
    do_not_increment_build_number: true
build:
    verbosity: minimal
test_script:
    # https://www.appveyor.com/docs/running-tests/
    - cmd: vstest.console /logger:Appveyor x64\Release\Calculator.Tests.dll /Platform:x64 /inIsolation
artifacts:
    - path: x64\Release\Calculator.lib